name: Cypress End-to-end Tests
on:
    workflow_run:
        workflows: ["Layered Preview Build"]
        types:
            - completed
jobs:
    cypress:
        runs-on: ubuntu-latest
        if: >
            ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
        steps:
            - uses: actions/checkout@v2
            - name: 'Download artifact'
              uses: actions/github-script@v3.1.0
              with:
                script: |
                  var artifacts = await github.actions.listWorkflowRunArtifacts({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     run_id: ${{github.event.workflow_run.id }},
                  });
                  var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
                    return artifact.name == "previewbuild"
                  })[0];
                  var download = await github.actions.downloadArtifact({
                     owner: context.repo.owner,
                     repo: context.repo.repo,
                     artifact_id: matchArtifact.id,
                     archive_format: 'zip',
                  });
                  var fs = require('fs');
                  fs.writeFileSync('${{github.workspace}}/previewbuild.zip', Buffer.from(download.data));
            - name: Extract Artifacts
              run: unzip -d webapp previewbuild.zip && rm previewbuild.zip
            - name: Run Cypress tests
              uses: cypress-io/github-action@v2
              with:
                  # The built in Electron runner seems to grind to a halt trying
                  # to run the tests, so use chrome.
                  browser: chrome
                  start: npx serve -p 8080 webapp
            - name: Upload Artifact
              if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: cypress-results
                  path: |
                      cypress/screenshots
                      cypress/videos
                      cypress/synapselogs
